
// Auto-generated by generate-color-tokens.ts
// Do not edit this file manually
#pragma once
#ifndef __SPECTRUM_TOKENS_HPP
#define __SPECTRUM_TOKENS_HPP

#include "../deps/imgui/imgui.h"

struct SpectrumTokens {
  ImVec4 accentBackgroundColorDefault;
  ImVec4 accentBackgroundColorDown;
  ImVec4 accentBackgroundColorHover;
  ImVec4 accentBackgroundColorKeyFocus;
  ImVec4 accentColor100;
  ImVec4 accentColor1000;
  ImVec4 accentColor1100;
  ImVec4 accentColor1200;
  ImVec4 accentColor1300;
  ImVec4 accentColor1400;
  ImVec4 accentColor200;
  ImVec4 accentColor300;
  ImVec4 accentColor400;
  ImVec4 accentColor500;
  ImVec4 accentColor600;
  ImVec4 accentColor700;
  ImVec4 accentColor800;
  ImVec4 accentColor900;
  ImVec4 accentContentColorDefault;
  ImVec4 accentContentColorDown;
  ImVec4 accentContentColorHover;
  ImVec4 accentContentColorKeyFocus;
  ImVec4 accentVisualColor;
  ImVec4 backgroundBaseColor;
  ImVec4 backgroundLayer1Color;
  ImVec4 backgroundLayer2Color;
  ImVec4 black;
  ImVec4 blue100;
  ImVec4 blue1000;
  ImVec4 blue1100;
  ImVec4 blue1200;
  ImVec4 blue1300;
  ImVec4 blue1400;
  ImVec4 blue200;
  ImVec4 blue300;
  ImVec4 blue400;
  ImVec4 blue500;
  ImVec4 blue600;
  ImVec4 blue700;
  ImVec4 blue800;
  ImVec4 blue900;
  ImVec4 blueBackgroundColorDefault;
  ImVec4 blueVisualColor;
  ImVec4 bodyColor;
  ImVec4 borderWidth100;
  ImVec4 cardSelectionBackgroundColor;
  ImVec4 celery100;
  ImVec4 celery1000;
  ImVec4 celery1100;
  ImVec4 celery1200;
  ImVec4 celery1300;
  ImVec4 celery1400;
  ImVec4 celery200;
  ImVec4 celery300;
  ImVec4 celery400;
  ImVec4 celery500;
  ImVec4 celery600;
  ImVec4 celery700;
  ImVec4 celery800;
  ImVec4 celery900;
  ImVec4 celeryBackgroundColorDefault;
  ImVec4 celeryVisualColor;
  ImVec4 chartreuse100;
  ImVec4 chartreuse1000;
  ImVec4 chartreuse1100;
  ImVec4 chartreuse1200;
  ImVec4 chartreuse1300;
  ImVec4 chartreuse1400;
  ImVec4 chartreuse200;
  ImVec4 chartreuse300;
  ImVec4 chartreuse400;
  ImVec4 chartreuse500;
  ImVec4 chartreuse600;
  ImVec4 chartreuse700;
  ImVec4 chartreuse800;
  ImVec4 chartreuse900;
  ImVec4 chartreuseBackgroundColorDefault;
  ImVec4 chartreuseVisualColor;
  ImVec4 coachMarkPaginationColor;
  ImVec4 codeColor;
  ImVec4 colorAreaBorderColor;
  ImVec4 colorAreaBorderWidth;
  ImVec4 colorHandleDropShadowColor;
  ImVec4 colorHandleInnerBorderColor;
  ImVec4 colorHandleOuterBorderColor;
  ImVec4 colorLoupeDropShadowColor;
  ImVec4 colorLoupeInnerBorder;
  ImVec4 colorLoupeOuterBorder;
  ImVec4 colorSliderBorderColor;
  ImVec4 cornerRadius75;
  ImVec4 cyan100;
  ImVec4 cyan1000;
  ImVec4 cyan1100;
  ImVec4 cyan1200;
  ImVec4 cyan1300;
  ImVec4 cyan1400;
  ImVec4 cyan200;
  ImVec4 cyan300;
  ImVec4 cyan400;
  ImVec4 cyan500;
  ImVec4 cyan600;
  ImVec4 cyan700;
  ImVec4 cyan800;
  ImVec4 cyan900;
  ImVec4 cyanBackgroundColorDefault;
  ImVec4 cyanVisualColor;
  ImVec4 detailColor;
  ImVec4 disabledBackgroundColor;
  ImVec4 disabledBorderColor;
  ImVec4 disabledContentColor;
  ImVec4 disabledStaticBlackBackgroundColor;
  ImVec4 disabledStaticBlackBorderColor;
  ImVec4 disabledStaticBlackContentColor;
  ImVec4 disabledStaticWhiteBackgroundColor;
  ImVec4 disabledStaticWhiteBorderColor;
  ImVec4 disabledStaticWhiteContentColor;
  ImVec4 dropShadowColor;
  ImVec4 dropShadowX;
  ImVec4 dropZoneBackgroundColor;
  ImVec4 floatingActionButtonDropShadowColor;
  ImVec4 floatingActionButtonShadowColor;
  ImVec4 focusIndicatorColor;
  ImVec4 fuchsia100;
  ImVec4 fuchsia1000;
  ImVec4 fuchsia1100;
  ImVec4 fuchsia1200;
  ImVec4 fuchsia1300;
  ImVec4 fuchsia1400;
  ImVec4 fuchsia200;
  ImVec4 fuchsia300;
  ImVec4 fuchsia400;
  ImVec4 fuchsia500;
  ImVec4 fuchsia600;
  ImVec4 fuchsia700;
  ImVec4 fuchsia800;
  ImVec4 fuchsia900;
  ImVec4 fuchsiaBackgroundColorDefault;
  ImVec4 fuchsiaVisualColor;
  ImVec4 gray100;
  ImVec4 gray200;
  ImVec4 gray300;
  ImVec4 gray400;
  ImVec4 gray50;
  ImVec4 gray500;
  ImVec4 gray600;
  ImVec4 gray700;
  ImVec4 gray75;
  ImVec4 gray800;
  ImVec4 gray900;
  ImVec4 grayBackgroundColorDefault;
  ImVec4 grayVisualColor;
  ImVec4 green100;
  ImVec4 green1000;
  ImVec4 green1100;
  ImVec4 green1200;
  ImVec4 green1300;
  ImVec4 green1400;
  ImVec4 green200;
  ImVec4 green300;
  ImVec4 green400;
  ImVec4 green500;
  ImVec4 green600;
  ImVec4 green700;
  ImVec4 green800;
  ImVec4 green900;
  ImVec4 greenBackgroundColorDefault;
  ImVec4 greenVisualColor;
  ImVec4 headingCjkFontWeight;
  ImVec4 headingColor;
  ImVec4 headingSansSerifEmphasizedFontWeight;
  ImVec4 headingSansSerifFontWeight;
  ImVec4 headingSerifEmphasizedFontWeight;
  ImVec4 headingSerifFontWeight;
  ImVec4 iconColorBluePrimaryDefault;
  ImVec4 iconColorGreenPrimaryDefault;
  ImVec4 iconColorInverse;
  ImVec4 iconColorPrimaryDefault;
  ImVec4 iconColorRedPrimaryDefault;
  ImVec4 iconColorYellowPrimaryDefault;
  ImVec4 inFieldButtonEdgeToFill;
  ImVec4 inFieldButtonFillStackedInnerBorderRounding;
  ImVec4 inFieldButtonInnerEdgeToDisclosureIconStackedExtraLarge;
  ImVec4 inFieldButtonInnerEdgeToDisclosureIconStackedLarge;
  ImVec4 inFieldButtonInnerEdgeToDisclosureIconStackedMedium;
  ImVec4 inFieldButtonInnerEdgeToDisclosureIconStackedSmall;
  ImVec4 inFieldButtonOuterEdgeToDisclosureIconStackedExtraLarge;
  ImVec4 inFieldButtonOuterEdgeToDisclosureIconStackedLarge;
  ImVec4 inFieldButtonOuterEdgeToDisclosureIconStackedMedium;
  ImVec4 inFieldButtonStackedInnerEdgeToFill;
  ImVec4 indigo100;
  ImVec4 indigo1000;
  ImVec4 indigo1100;
  ImVec4 indigo1200;
  ImVec4 indigo1300;
  ImVec4 indigo1400;
  ImVec4 indigo200;
  ImVec4 indigo300;
  ImVec4 indigo400;
  ImVec4 indigo500;
  ImVec4 indigo600;
  ImVec4 indigo700;
  ImVec4 indigo800;
  ImVec4 indigo900;
  ImVec4 indigoBackgroundColorDefault;
  ImVec4 indigoVisualColor;
  ImVec4 informativeBackgroundColorDefault;
  ImVec4 informativeBackgroundColorDown;
  ImVec4 informativeBackgroundColorHover;
  ImVec4 informativeBackgroundColorKeyFocus;
  ImVec4 informativeColor100;
  ImVec4 informativeColor1000;
  ImVec4 informativeColor1100;
  ImVec4 informativeColor1200;
  ImVec4 informativeColor1300;
  ImVec4 informativeColor1400;
  ImVec4 informativeColor200;
  ImVec4 informativeColor300;
  ImVec4 informativeColor400;
  ImVec4 informativeColor500;
  ImVec4 informativeColor600;
  ImVec4 informativeColor700;
  ImVec4 informativeColor800;
  ImVec4 informativeColor900;
  ImVec4 informativeVisualColor;
  ImVec4 magenta100;
  ImVec4 magenta1000;
  ImVec4 magenta1100;
  ImVec4 magenta1200;
  ImVec4 magenta1300;
  ImVec4 magenta1400;
  ImVec4 magenta200;
  ImVec4 magenta300;
  ImVec4 magenta400;
  ImVec4 magenta500;
  ImVec4 magenta600;
  ImVec4 magenta700;
  ImVec4 magenta800;
  ImVec4 magenta900;
  ImVec4 magentaBackgroundColorDefault;
  ImVec4 magentaVisualColor;
  ImVec4 negativeBackgroundColorDefault;
  ImVec4 negativeBackgroundColorDown;
  ImVec4 negativeBackgroundColorHover;
  ImVec4 negativeBackgroundColorKeyFocus;
  ImVec4 negativeBorderColorDefault;
  ImVec4 negativeBorderColorDown;
  ImVec4 negativeBorderColorFocus;
  ImVec4 negativeBorderColorFocusHover;
  ImVec4 negativeBorderColorHover;
  ImVec4 negativeBorderColorKeyFocus;
  ImVec4 negativeColor100;
  ImVec4 negativeColor1000;
  ImVec4 negativeColor1100;
  ImVec4 negativeColor1200;
  ImVec4 negativeColor1300;
  ImVec4 negativeColor1400;
  ImVec4 negativeColor200;
  ImVec4 negativeColor300;
  ImVec4 negativeColor400;
  ImVec4 negativeColor500;
  ImVec4 negativeColor600;
  ImVec4 negativeColor700;
  ImVec4 negativeColor800;
  ImVec4 negativeColor900;
  ImVec4 negativeContentColorDefault;
  ImVec4 negativeContentColorDown;
  ImVec4 negativeContentColorHover;
  ImVec4 negativeContentColorKeyFocus;
  ImVec4 negativeVisualColor;
  ImVec4 neutralBackgroundColorDefault;
  ImVec4 neutralBackgroundColorDown;
  ImVec4 neutralBackgroundColorHover;
  ImVec4 neutralBackgroundColorKeyFocus;
  ImVec4 neutralBackgroundColorSelectedDefault;
  ImVec4 neutralBackgroundColorSelectedDown;
  ImVec4 neutralBackgroundColorSelectedHover;
  ImVec4 neutralBackgroundColorSelectedKeyFocus;
  ImVec4 neutralContentColorDefault;
  ImVec4 neutralContentColorDown;
  ImVec4 neutralContentColorFocus;
  ImVec4 neutralContentColorFocusHover;
  ImVec4 neutralContentColorHover;
  ImVec4 neutralContentColorKeyFocus;
  ImVec4 neutralSubduedBackgroundColorDefault;
  ImVec4 neutralSubduedBackgroundColorDown;
  ImVec4 neutralSubduedBackgroundColorHover;
  ImVec4 neutralSubduedBackgroundColorKeyFocus;
  ImVec4 neutralSubduedContentColorDefault;
  ImVec4 neutralSubduedContentColorDown;
  ImVec4 neutralSubduedContentColorHover;
  ImVec4 neutralSubduedContentColorKeyFocus;
  ImVec4 neutralSubduedContentColorSelected;
  ImVec4 neutralVisualColor;
  ImVec4 noticeBackgroundColorDefault;
  ImVec4 noticeColor100;
  ImVec4 noticeColor1000;
  ImVec4 noticeColor1100;
  ImVec4 noticeColor1200;
  ImVec4 noticeColor1300;
  ImVec4 noticeColor1400;
  ImVec4 noticeColor200;
  ImVec4 noticeColor300;
  ImVec4 noticeColor400;
  ImVec4 noticeColor500;
  ImVec4 noticeColor600;
  ImVec4 noticeColor700;
  ImVec4 noticeColor800;
  ImVec4 noticeColor900;
  ImVec4 noticeVisualColor;
  ImVec4 opacityCheckerboardSquareDark;
  ImVec4 opacityCheckerboardSquareLight;
  ImVec4 orange100;
  ImVec4 orange1000;
  ImVec4 orange1100;
  ImVec4 orange1200;
  ImVec4 orange1300;
  ImVec4 orange1400;
  ImVec4 orange200;
  ImVec4 orange300;
  ImVec4 orange400;
  ImVec4 orange500;
  ImVec4 orange600;
  ImVec4 orange700;
  ImVec4 orange800;
  ImVec4 orange900;
  ImVec4 orangeBackgroundColorDefault;
  ImVec4 orangeVisualColor;
  ImVec4 overlayColor;
  ImVec4 overlayOpacity;
  ImVec4 pickerBorderWidth;
  ImVec4 positiveBackgroundColorDefault;
  ImVec4 positiveBackgroundColorDown;
  ImVec4 positiveBackgroundColorHover;
  ImVec4 positiveBackgroundColorKeyFocus;
  ImVec4 positiveColor100;
  ImVec4 positiveColor1000;
  ImVec4 positiveColor1100;
  ImVec4 positiveColor1200;
  ImVec4 positiveColor1300;
  ImVec4 positiveColor1400;
  ImVec4 positiveColor200;
  ImVec4 positiveColor300;
  ImVec4 positiveColor400;
  ImVec4 positiveColor500;
  ImVec4 positiveColor600;
  ImVec4 positiveColor700;
  ImVec4 positiveColor800;
  ImVec4 positiveColor900;
  ImVec4 positiveVisualColor;
  ImVec4 purple100;
  ImVec4 purple1000;
  ImVec4 purple1100;
  ImVec4 purple1200;
  ImVec4 purple1300;
  ImVec4 purple1400;
  ImVec4 purple200;
  ImVec4 purple300;
  ImVec4 purple400;
  ImVec4 purple500;
  ImVec4 purple600;
  ImVec4 purple700;
  ImVec4 purple800;
  ImVec4 purple900;
  ImVec4 purpleBackgroundColorDefault;
  ImVec4 purpleVisualColor;
  ImVec4 red100;
  ImVec4 red1000;
  ImVec4 red1100;
  ImVec4 red1200;
  ImVec4 red1300;
  ImVec4 red1400;
  ImVec4 red200;
  ImVec4 red300;
  ImVec4 red400;
  ImVec4 red500;
  ImVec4 red600;
  ImVec4 red700;
  ImVec4 red800;
  ImVec4 red900;
  ImVec4 redBackgroundColorDefault;
  ImVec4 redVisualColor;
  ImVec4 seafoam100;
  ImVec4 seafoam1000;
  ImVec4 seafoam1100;
  ImVec4 seafoam1200;
  ImVec4 seafoam1300;
  ImVec4 seafoam1400;
  ImVec4 seafoam200;
  ImVec4 seafoam300;
  ImVec4 seafoam400;
  ImVec4 seafoam500;
  ImVec4 seafoam600;
  ImVec4 seafoam700;
  ImVec4 seafoam800;
  ImVec4 seafoam900;
  ImVec4 seafoamBackgroundColorDefault;
  ImVec4 seafoamVisualColor;
  ImVec4 sliderHandleGap;
  ImVec4 sliderTrackThickness;
  ImVec4 staticBlackFocusIndicatorColor;
  ImVec4 staticBlue1000;
  ImVec4 staticBlue900;
  ImVec4 staticFuchsia1000;
  ImVec4 staticFuchsia900;
  ImVec4 staticIndigo1000;
  ImVec4 staticIndigo900;
  ImVec4 staticMagenta1000;
  ImVec4 staticMagenta900;
  ImVec4 staticRed1000;
  ImVec4 staticRed900;
  ImVec4 staticWhiteFocusIndicatorColor;
  ImVec4 swatchBorderColor;
  ImVec4 swatchDisabledIconBorderColor;
  ImVec4 tableRowHoverColor;
  ImVec4 tableSelectedRowBackgroundColor;
  ImVec4 tableSelectedRowBackgroundColorNonEmphasized;
  ImVec4 thumbnailBorderColor;
  ImVec4 transparentBlack100;
  ImVec4 transparentBlack200;
  ImVec4 transparentBlack300;
  ImVec4 transparentBlack400;
  ImVec4 transparentBlack500;
  ImVec4 transparentBlack600;
  ImVec4 transparentBlack700;
  ImVec4 transparentBlack800;
  ImVec4 transparentBlack900;
  ImVec4 transparentWhite100;
  ImVec4 transparentWhite200;
  ImVec4 transparentWhite300;
  ImVec4 transparentWhite400;
  ImVec4 transparentWhite500;
  ImVec4 transparentWhite600;
  ImVec4 transparentWhite700;
  ImVec4 transparentWhite800;
  ImVec4 transparentWhite900;
  ImVec4 white;
  ImVec4 yellow100;
  ImVec4 yellow1000;
  ImVec4 yellow1100;
  ImVec4 yellow1200;
  ImVec4 yellow1300;
  ImVec4 yellow1400;
  ImVec4 yellow200;
  ImVec4 yellow300;
  ImVec4 yellow400;
  ImVec4 yellow500;
  ImVec4 yellow600;
  ImVec4 yellow700;
  ImVec4 yellow800;
  ImVec4 yellow900;
  ImVec4 yellowBackgroundColorDefault;
  ImVec4 yellowVisualColor;
};

static const SpectrumTokens spectrumLight{
    .accentBackgroundColorDefault     = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .accentBackgroundColorDown        = ImVec4(0.0f, 0.2667f, 0.5686f, 1.0f),
    .accentBackgroundColorHover       = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .accentBackgroundColorKeyFocus    = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .accentColor100                   = ImVec4(0.8784f, 0.949f, 1.0f, 1.0f),
    .accentColor1000                  = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .accentColor1100                  = ImVec4(0.0f, 0.2667f, 0.5686f, 1.0f),
    .accentColor1200                  = ImVec4(0.0f, 0.2078f, 0.4431f, 1.0f),
    .accentColor1300                  = ImVec4(0.0f, 0.1529f, 0.3294f, 1.0f),
    .accentColor1400                  = ImVec4(0.0f, 0.1098f, 0.2353f, 1.0f),
    .accentColor200                   = ImVec4(0.7922f, 0.9098f, 1.0f, 1.0f),
    .accentColor300                   = ImVec4(0.7098f, 0.8706f, 1.0f, 1.0f),
    .accentColor400                   = ImVec4(0.5882f, 0.8078f, 0.9922f, 1.0f),
    .accentColor500                   = ImVec4(0.4706f, 0.7333f, 0.9804f, 1.0f),
    .accentColor600                   = ImVec4(0.349f, 0.6549f, 0.9647f, 1.0f),
    .accentColor700                   = ImVec4(0.2196f, 0.5725f, 0.9529f, 1.0f),
    .accentColor800                   = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .accentColor900                   = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .accentContentColorDefault        = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .accentContentColorDown           = ImVec4(0.0f, 0.2667f, 0.5686f, 1.0f),
    .accentContentColorHover          = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .accentContentColorKeyFocus       = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .accentVisualColor                = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .backgroundBaseColor              = ImVec4(0.902f, 0.902f, 0.902f, 1.0f),
    .backgroundLayer1Color            = ImVec4(0.9725f, 0.9725f, 0.9725f, 1.0f),
    .backgroundLayer2Color            = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .black                            = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .blue100                          = ImVec4(0.8784f, 0.949f, 1.0f, 1.0f),
    .blue1000                         = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .blue1100                         = ImVec4(0.0f, 0.2667f, 0.5686f, 1.0f),
    .blue1200                         = ImVec4(0.0f, 0.2078f, 0.4431f, 1.0f),
    .blue1300                         = ImVec4(0.0f, 0.1529f, 0.3294f, 1.0f),
    .blue1400                         = ImVec4(0.0f, 0.1098f, 0.2353f, 1.0f),
    .blue200                          = ImVec4(0.7922f, 0.9098f, 1.0f, 1.0f),
    .blue300                          = ImVec4(0.7098f, 0.8706f, 1.0f, 1.0f),
    .blue400                          = ImVec4(0.5882f, 0.8078f, 0.9922f, 1.0f),
    .blue500                          = ImVec4(0.4706f, 0.7333f, 0.9804f, 1.0f),
    .blue600                          = ImVec4(0.349f, 0.6549f, 0.9647f, 1.0f),
    .blue700                          = ImVec4(0.2196f, 0.5725f, 0.9529f, 1.0f),
    .blue800                          = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .blue900                          = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .blueBackgroundColorDefault       = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .blueVisualColor                  = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .bodyColor                        = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .cardSelectionBackgroundColor     = ImVec4(0.9725f, 0.9725f, 0.9725f, 1.0f),
    .celery100                        = ImVec4(0.8039f, 0.9882f, 0.749f, 1.0f),
    .celery1000                       = ImVec4(0.0f, 0.4039f, 0.0588f, 1.0f),
    .celery1100                       = ImVec4(0.0f, 0.3255f, 0.051f, 1.0f),
    .celery1200                       = ImVec4(0.0f, 0.251f, 0.0392f, 1.0f),
    .celery1300                       = ImVec4(0.0f, 0.1882f, 0.0275f, 1.0f),
    .celery1400                       = ImVec4(0.0f, 0.1333f, 0.0196f, 1.0f),
    .celery200                        = ImVec4(0.6824f, 0.9647f, 0.6157f, 1.0f),
    .celery300                        = ImVec4(0.5882f, 0.9333f, 0.5216f, 1.0f),
    .celery400                        = ImVec4(0.4471f, 0.8784f, 0.4157f, 1.0f),
    .celery500                        = ImVec4(0.3059f, 0.8118f, 0.3137f, 1.0f),
    .celery600                        = ImVec4(0.1529f, 0.7333f, 0.2118f, 1.0f),
    .celery700                        = ImVec4(0.0275f, 0.6549f, 0.1294f, 1.0f),
    .celery800                        = ImVec4(0.0f, 0.5686f, 0.0706f, 1.0f),
    .celery900                        = ImVec4(0.0f, 0.4863f, 0.0588f, 1.0f),
    .celeryBackgroundColorDefault     = ImVec4(0.1529f, 0.7333f, 0.2118f, 1.0f),
    .celeryVisualColor                = ImVec4(0.0275f, 0.6549f, 0.1294f, 1.0f),
    .chartreuse100                    = ImVec4(0.8588f, 0.9882f, 0.4314f, 1.0f),
    .chartreuse1000                   = ImVec4(0.2824f, 0.3765f, 0.0f, 1.0f),
    .chartreuse1100                   = ImVec4(0.2275f, 0.302f, 0.0f, 1.0f),
    .chartreuse1200                   = ImVec4(0.1725f, 0.2314f, 0.0f, 1.0f),
    .chartreuse1300                   = ImVec4(0.1294f, 0.1725f, 0.0f, 1.0f),
    .chartreuse1400                   = ImVec4(0.0941f, 0.1216f, 0.0f, 1.0f),
    .chartreuse200                    = ImVec4(0.7961f, 0.9569f, 0.2627f, 1.0f),
    .chartreuse300                    = ImVec4(0.7373f, 0.9137f, 0.1647f, 1.0f),
    .chartreuse400                    = ImVec4(0.6667f, 0.8471f, 0.0863f, 1.0f),
    .chartreuse500                    = ImVec4(0.5961f, 0.7725f, 0.0392f, 1.0f),
    .chartreuse600                    = ImVec4(0.5294f, 0.6941f, 0.0118f, 1.0f),
    .chartreuse700                    = ImVec4(0.4627f, 0.6118f, 0.0f, 1.0f),
    .chartreuse800                    = ImVec4(0.4039f, 0.5333f, 0.0f, 1.0f),
    .chartreuse900                    = ImVec4(0.3412f, 0.4549f, 0.0f, 1.0f),
    .chartreuseBackgroundColorDefault = ImVec4(0.5961f, 0.7725f, 0.0392f, 1.0f),
    .chartreuseVisualColor            = ImVec4(0.5294f, 0.6941f, 0.0118f, 1.0f),
    .coachMarkPaginationColor         = ImVec4(0.4275f, 0.4275f, 0.4275f, 1.0f),
    .codeColor                        = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .colorAreaBorderColor             = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorHandleDropShadowColor       = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorHandleInnerBorderColor      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorHandleOuterBorderColor      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorLoupeDropShadowColor        = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorLoupeInnerBorder            = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorLoupeOuterBorder            = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .colorSliderBorderColor           = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .cyan100                          = ImVec4(0.7725f, 0.9725f, 1.0f, 1.0f),
    .cyan1000                         = ImVec4(0.0f, 0.3647f, 0.5373f, 1.0f),
    .cyan1100                         = ImVec4(0.0f, 0.2902f, 0.451f, 1.0f),
    .cyan1200                         = ImVec4(0.0f, 0.2235f, 0.3647f, 1.0f),
    .cyan1300                         = ImVec4(0.0f, 0.1647f, 0.2745f, 1.0f),
    .cyan1400                         = ImVec4(0.0f, 0.1176f, 0.2f, 1.0f),
    .cyan200                          = ImVec4(0.6431f, 0.9412f, 1.0f, 1.0f),
    .cyan300                          = ImVec4(0.5333f, 0.9059f, 0.9804f, 1.0f),
    .cyan400                          = ImVec4(0.3765f, 0.8471f, 0.9529f, 1.0f),
    .cyan500                          = ImVec4(0.2f, 0.7725f, 0.9098f, 1.0f),
    .cyan600                          = ImVec4(0.0706f, 0.6902f, 0.8549f, 1.0f),
    .cyan700                          = ImVec4(0.0039f, 0.6118f, 0.7843f, 1.0f),
    .cyan800                          = ImVec4(0.0f, 0.5255f, 0.7059f, 1.0f),
    .cyan900                          = ImVec4(0.0f, 0.4431f, 0.6235f, 1.0f),
    .cyanBackgroundColorDefault       = ImVec4(0.0f, 0.4431f, 0.6235f, 1.0f),
    .cyanVisualColor                  = ImVec4(0.0706f, 0.6902f, 0.8549f, 1.0f),
    .detailColor                      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .disabledBackgroundColor          = ImVec4(0.902f, 0.902f, 0.902f, 1.0f),
    .disabledBorderColor              = ImVec4(0.8353f, 0.8353f, 0.8353f, 1.0f),
    .disabledContentColor             = ImVec4(0.6941f, 0.6941f, 0.6941f, 1.0f),
    .disabledStaticBlackBackgroundColor = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .disabledStaticBlackBorderColor     = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .disabledStaticBlackContentColor    = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .disabledStaticWhiteBackgroundColor = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .disabledStaticWhiteBorderColor     = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .disabledStaticWhiteContentColor    = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .dropShadowColor                    = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .dropZoneBackgroundColor = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .floatingActionButtonDropShadowColor = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .floatingActionButtonShadowColor     = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .focusIndicatorColor           = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .fuchsia100                    = ImVec4(1.0f, 0.9137f, 0.9882f, 1.0f),
    .fuchsia1000                   = ImVec4(0.6157f, 0.0118f, 0.6196f, 1.0f),
    .fuchsia1100                   = ImVec4(0.502f, 0.0f, 0.5059f, 1.0f),
    .fuchsia1200                   = ImVec4(0.3922f, 0.0235f, 0.3922f, 1.0f),
    .fuchsia1300                   = ImVec4(0.2784f, 0.0549f, 0.2745f, 1.0f),
    .fuchsia1400                   = ImVec4(0.1961f, 0.051f, 0.1922f, 1.0f),
    .fuchsia200                    = ImVec4(1.0f, 0.8549f, 0.9804f, 1.0f),
    .fuchsia300                    = ImVec4(0.9961f, 0.7804f, 0.9725f, 1.0f),
    .fuchsia400                    = ImVec4(0.9843f, 0.6824f, 0.9647f, 1.0f),
    .fuchsia500                    = ImVec4(0.9608f, 0.5725f, 0.9529f, 1.0f),
    .fuchsia600                    = ImVec4(0.9294f, 0.4549f, 0.9294f, 1.0f),
    .fuchsia700                    = ImVec4(0.8784f, 0.3333f, 0.8863f, 1.0f),
    .fuchsia800                    = ImVec4(0.8039f, 0.2275f, 0.8078f, 1.0f),
    .fuchsia900                    = ImVec4(0.7137f, 0.1333f, 0.7176f, 1.0f),
    .fuchsiaBackgroundColorDefault = ImVec4(0.7137f, 0.1333f, 0.7176f, 1.0f),
    .fuchsiaVisualColor            = ImVec4(0.8039f, 0.2275f, 0.8078f, 1.0f),
    .gray100                       = ImVec4(0.9725f, 0.9725f, 0.9725f, 1.0f),
    .gray200                       = ImVec4(0.902f, 0.902f, 0.902f, 1.0f),
    .gray300                       = ImVec4(0.8353f, 0.8353f, 0.8353f, 1.0f),
    .gray400                       = ImVec4(0.6941f, 0.6941f, 0.6941f, 1.0f),
    .gray50                        = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .gray500                       = ImVec4(0.5647f, 0.5647f, 0.5647f, 1.0f),
    .gray600                       = ImVec4(0.4275f, 0.4275f, 0.4275f, 1.0f),
    .gray700                       = ImVec4(0.2745f, 0.2745f, 0.2745f, 1.0f),
    .gray75                        = ImVec4(0.9922f, 0.9922f, 0.9922f, 1.0f),
    .gray800                       = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .gray900                       = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .grayBackgroundColorDefault    = ImVec4(0.2745f, 0.2745f, 0.2745f, 1.0f),
    .grayVisualColor               = ImVec4(0.5647f, 0.5647f, 0.5647f, 1.0f),
    .green100                      = ImVec4(0.8078f, 0.9725f, 0.8784f, 1.0f),
    .green1000                     = ImVec4(0.0f, 0.3961f, 0.2431f, 1.0f),
    .green1100                     = ImVec4(0.0f, 0.3176f, 0.1961f, 1.0f),
    .green1200                     = ImVec4(0.0196f, 0.2471f, 0.1529f, 1.0f),
    .green1300                     = ImVec4(0.0392f, 0.1804f, 0.1137f, 1.0f),
    .green1400                     = ImVec4(0.0392f, 0.1255f, 0.0824f, 1.0f),
    .green200                      = ImVec4(0.6784f, 0.9569f, 0.8078f, 1.0f),
    .green300                      = ImVec4(0.5373f, 0.9255f, 0.7373f, 1.0f),
    .green400                      = ImVec4(0.4039f, 0.8706f, 0.6588f, 1.0f),
    .green500                      = ImVec4(0.2863f, 0.8f, 0.5765f, 1.0f),
    .green600                      = ImVec4(0.1843f, 0.7216f, 0.502f, 1.0f),
    .green700                      = ImVec4(0.0824f, 0.6431f, 0.4314f, 1.0f),
    .green800                      = ImVec4(0.0f, 0.5608f, 0.3647f, 1.0f),
    .green900                      = ImVec4(0.0f, 0.4784f, 0.302f, 1.0f),
    .greenBackgroundColorDefault   = ImVec4(0.0f, 0.4784f, 0.302f, 1.0f),
    .greenVisualColor              = ImVec4(0.0824f, 0.6431f, 0.4314f, 1.0f),
    .headingColor                  = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .iconColorBluePrimaryDefault   = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .iconColorGreenPrimaryDefault  = ImVec4(0.0f, 0.4784f, 0.302f, 1.0f),
    .iconColorInverse              = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .iconColorPrimaryDefault       = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .iconColorRedPrimaryDefault    = ImVec4(0.8275f, 0.0824f, 0.0627f, 1.0f),
    .iconColorYellowPrimaryDefault = ImVec4(0.9098f, 0.7765f, 0.0f, 1.0f),
    .indigo100                     = ImVec4(0.9294f, 0.9333f, 1.0f, 1.0f),
    .indigo1000                    = ImVec4(0.251f, 0.2745f, 0.7922f, 1.0f),
    .indigo1100                    = ImVec4(0.1961f, 0.2118f, 0.6588f, 1.0f),
    .indigo1200                    = ImVec4(0.149f, 0.1608f, 0.5255f, 1.0f),
    .indigo1300                    = ImVec4(0.1059f, 0.1176f, 0.3922f, 1.0f),
    .indigo1400                    = ImVec4(0.0784f, 0.0863f, 0.2824f, 1.0f),
    .indigo200                     = ImVec4(0.8784f, 0.8863f, 1.0f, 1.0f),
    .indigo300                     = ImVec4(0.8275f, 0.8353f, 1.0f, 1.0f),
    .indigo400                     = ImVec4(0.7569f, 0.7686f, 1.0f, 1.0f),
    .indigo500                     = ImVec4(0.6745f, 0.6863f, 1.0f, 1.0f),
    .indigo600                     = ImVec4(0.5843f, 0.6f, 1.0f, 1.0f),
    .indigo700                     = ImVec4(0.4941f, 0.5176f, 0.9882f, 1.0f),
    .indigo800                     = ImVec4(0.4078f, 0.4275f, 0.9569f, 1.0f),
    .indigo900                     = ImVec4(0.3216f, 0.3451f, 0.8941f, 1.0f),
    .indigoBackgroundColorDefault  = ImVec4(0.3216f, 0.3451f, 0.8941f, 1.0f),
    .indigoVisualColor             = ImVec4(0.4078f, 0.4275f, 0.9569f, 1.0f),
    .informativeBackgroundColorDefault =
        ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .informativeBackgroundColorDown     = ImVec4(0.0f, 0.2667f, 0.5686f, 1.0f),
    .informativeBackgroundColorHover    = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .informativeBackgroundColorKeyFocus = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .informativeColor100                = ImVec4(0.8784f, 0.949f, 1.0f, 1.0f),
    .informativeColor1000               = ImVec4(0.0f, 0.3294f, 0.7137f, 1.0f),
    .informativeColor1100               = ImVec4(0.0f, 0.2667f, 0.5686f, 1.0f),
    .informativeColor1200               = ImVec4(0.0f, 0.2078f, 0.4431f, 1.0f),
    .informativeColor1300               = ImVec4(0.0f, 0.1529f, 0.3294f, 1.0f),
    .informativeColor1400               = ImVec4(0.0f, 0.1098f, 0.2353f, 1.0f),
    .informativeColor200                = ImVec4(0.7922f, 0.9098f, 1.0f, 1.0f),
    .informativeColor300                = ImVec4(0.7098f, 0.8706f, 1.0f, 1.0f),
    .informativeColor400             = ImVec4(0.5882f, 0.8078f, 0.9922f, 1.0f),
    .informativeColor500             = ImVec4(0.4706f, 0.7333f, 0.9804f, 1.0f),
    .informativeColor600             = ImVec4(0.349f, 0.6549f, 0.9647f, 1.0f),
    .informativeColor700             = ImVec4(0.2196f, 0.5725f, 0.9529f, 1.0f),
    .informativeColor800             = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .informativeColor900             = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .informativeVisualColor          = ImVec4(0.0784f, 0.4784f, 0.9529f, 1.0f),
    .magenta100                      = ImVec4(1.0f, 0.9176f, 0.9451f, 1.0f),
    .magenta1000                     = ImVec4(0.6784f, 0.0353f, 0.3333f, 1.0f),
    .magenta1100                     = ImVec4(0.5569f, 0.0f, 0.2706f, 1.0f),
    .magenta1200                     = ImVec4(0.4392f, 0.0f, 0.2157f, 1.0f),
    .magenta1300                     = ImVec4(0.3294f, 0.0118f, 0.1647f, 1.0f),
    .magenta1400                     = ImVec4(0.2353f, 0.0235f, 0.1137f, 1.0f),
    .magenta200                      = ImVec4(1.0f, 0.8627f, 0.9098f, 1.0f),
    .magenta300                      = ImVec4(1.0f, 0.7922f, 0.8667f, 1.0f),
    .magenta400                      = ImVec4(1.0f, 0.698f, 0.8078f, 1.0f),
    .magenta500                      = ImVec4(1.0f, 0.5843f, 0.7412f, 1.0f),
    .magenta600                      = ImVec4(0.9804f, 0.4667f, 0.6667f, 1.0f),
    .magenta700                      = ImVec4(0.9373f, 0.3529f, 0.5961f, 1.0f),
    .magenta800                      = ImVec4(0.8706f, 0.2392f, 0.5098f, 1.0f),
    .magenta900                      = ImVec4(0.7843f, 0.1333f, 0.4118f, 1.0f),
    .magentaBackgroundColorDefault   = ImVec4(0.7843f, 0.1333f, 0.4118f, 1.0f),
    .magentaVisualColor              = ImVec4(0.8706f, 0.2392f, 0.5098f, 1.0f),
    .negativeBackgroundColorDefault  = ImVec4(0.8275f, 0.0824f, 0.0627f, 1.0f),
    .negativeBackgroundColorDown     = ImVec4(0.5765f, 0.0f, 0.0f, 1.0f),
    .negativeBackgroundColorHover    = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeBackgroundColorKeyFocus = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeBorderColorDefault      = ImVec4(0.8275f, 0.0824f, 0.0627f, 1.0f),
    .negativeBorderColorDown         = ImVec4(0.5765f, 0.0f, 0.0f, 1.0f),
    .negativeBorderColorFocus        = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeBorderColorFocusHover   = ImVec4(0.5765f, 0.0f, 0.0f, 1.0f),
    .negativeBorderColorHover        = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeBorderColorKeyFocus     = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeColor100                = ImVec4(1.0f, 0.9216f, 0.9059f, 1.0f),
    .negativeColor1000               = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeColor1100               = ImVec4(0.5765f, 0.0f, 0.0f, 1.0f),
    .negativeColor1200               = ImVec4(0.4549f, 0.0f, 0.0f, 1.0f),
    .negativeColor1300               = ImVec4(0.349f, 0.0f, 0.0f, 1.0f),
    .negativeColor1400               = ImVec4(0.2627f, 0.0f, 0.0f, 1.0f),
    .negativeColor200                = ImVec4(1.0f, 0.8667f, 0.8392f, 1.0f),
    .negativeColor300                = ImVec4(1.0f, 0.8039f, 0.7647f, 1.0f),
    .negativeColor400                = ImVec4(1.0f, 0.7176f, 0.6627f, 1.0f),
    .negativeColor500                = ImVec4(1.0f, 0.6078f, 0.5333f, 1.0f),
    .negativeColor600                = ImVec4(1.0f, 0.4863f, 0.3961f, 1.0f),
    .negativeColor700                = ImVec4(0.9686f, 0.3608f, 0.2745f, 1.0f),
    .negativeColor800                = ImVec4(0.9176f, 0.2196f, 0.1608f, 1.0f),
    .negativeColor900                = ImVec4(0.8275f, 0.0824f, 0.0627f, 1.0f),
    .negativeContentColorDefault     = ImVec4(0.8275f, 0.0824f, 0.0627f, 1.0f),
    .negativeContentColorDown        = ImVec4(0.5765f, 0.0f, 0.0f, 1.0f),
    .negativeContentColorHover       = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeContentColorKeyFocus    = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .negativeVisualColor             = ImVec4(0.9176f, 0.2196f, 0.1608f, 1.0f),
    .neutralBackgroundColorDefault   = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .neutralBackgroundColorDown      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralBackgroundColorHover     = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralBackgroundColorKeyFocus  = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralBackgroundColorSelectedDefault =
        ImVec4(0.2745f, 0.2745f, 0.2745f, 1.0f),
    .neutralBackgroundColorSelectedDown = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralBackgroundColorSelectedHover =
        ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .neutralBackgroundColorSelectedKeyFocus =
        ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .neutralContentColorDefault    = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .neutralContentColorDown       = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralContentColorFocus      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralContentColorFocusHover = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralContentColorHover      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralContentColorKeyFocus   = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralSubduedBackgroundColorDefault =
        ImVec4(0.4275f, 0.4275f, 0.4275f, 1.0f),
    .neutralSubduedBackgroundColorDown =
        ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .neutralSubduedBackgroundColorHover =
        ImVec4(0.2745f, 0.2745f, 0.2745f, 1.0f),
    .neutralSubduedBackgroundColorKeyFocus =
        ImVec4(0.2745f, 0.2745f, 0.2745f, 1.0f),
    .neutralSubduedContentColorDefault =
        ImVec4(0.2745f, 0.2745f, 0.2745f, 1.0f),
    .neutralSubduedContentColorDown  = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralSubduedContentColorHover = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .neutralSubduedContentColorKeyFocus =
        ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .neutralSubduedContentColorSelected = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .neutralVisualColor              = ImVec4(0.5647f, 0.5647f, 0.5647f, 1.0f),
    .noticeBackgroundColorDefault    = ImVec4(0.9647f, 0.5216f, 0.0667f, 1.0f),
    .noticeColor100                  = ImVec4(1.0f, 0.9255f, 0.8f, 1.0f),
    .noticeColor1000                 = ImVec4(0.5843f, 0.2392f, 0.0f, 1.0f),
    .noticeColor1100                 = ImVec4(0.4784f, 0.1843f, 0.0f, 1.0f),
    .noticeColor1200                 = ImVec4(0.3804f, 0.1373f, 0.0f, 1.0f),
    .noticeColor1300                 = ImVec4(0.2863f, 0.098f, 0.0039f, 1.0f),
    .noticeColor1400                 = ImVec4(0.2078f, 0.0706f, 0.0039f, 1.0f),
    .noticeColor200                  = ImVec4(1.0f, 0.8745f, 0.6784f, 1.0f),
    .noticeColor300                  = ImVec4(0.9922f, 0.8235f, 0.5686f, 1.0f),
    .noticeColor400                  = ImVec4(1.0f, 0.7333f, 0.3882f, 1.0f),
    .noticeColor500                  = ImVec4(1.0f, 0.6275f, 0.2157f, 1.0f),
    .noticeColor600                  = ImVec4(0.9647f, 0.5216f, 0.0667f, 1.0f),
    .noticeColor700                  = ImVec4(0.8941f, 0.4353f, 0.0f, 1.0f),
    .noticeColor800                  = ImVec4(0.7961f, 0.3647f, 0.0f, 1.0f),
    .noticeColor900                  = ImVec4(0.6941f, 0.298f, 0.0f, 1.0f),
    .noticeVisualColor               = ImVec4(0.8941f, 0.4353f, 0.0f, 1.0f),
    .opacityCheckerboardSquareDark   = ImVec4(0.902f, 0.902f, 0.902f, 1.0f),
    .opacityCheckerboardSquareLight  = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .orange100                       = ImVec4(1.0f, 0.9255f, 0.8f, 1.0f),
    .orange1000                      = ImVec4(0.5843f, 0.2392f, 0.0f, 1.0f),
    .orange1100                      = ImVec4(0.4784f, 0.1843f, 0.0f, 1.0f),
    .orange1200                      = ImVec4(0.3804f, 0.1373f, 0.0f, 1.0f),
    .orange1300                      = ImVec4(0.2863f, 0.098f, 0.0039f, 1.0f),
    .orange1400                      = ImVec4(0.2078f, 0.0706f, 0.0039f, 1.0f),
    .orange200                       = ImVec4(1.0f, 0.8745f, 0.6784f, 1.0f),
    .orange300                       = ImVec4(0.9922f, 0.8235f, 0.5686f, 1.0f),
    .orange400                       = ImVec4(1.0f, 0.7333f, 0.3882f, 1.0f),
    .orange500                       = ImVec4(1.0f, 0.6275f, 0.2157f, 1.0f),
    .orange600                       = ImVec4(0.9647f, 0.5216f, 0.0667f, 1.0f),
    .orange700                       = ImVec4(0.8941f, 0.4353f, 0.0f, 1.0f),
    .orange800                       = ImVec4(0.7961f, 0.3647f, 0.0f, 1.0f),
    .orange900                       = ImVec4(0.6941f, 0.298f, 0.0f, 1.0f),
    .orangeBackgroundColorDefault    = ImVec4(0.9647f, 0.5216f, 0.0667f, 1.0f),
    .orangeVisualColor               = ImVec4(0.8941f, 0.4353f, 0.0f, 1.0f),
    .overlayColor                    = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .positiveBackgroundColorDefault  = ImVec4(0.0f, 0.4784f, 0.302f, 1.0f),
    .positiveBackgroundColorDown     = ImVec4(0.0f, 0.3176f, 0.1961f, 1.0f),
    .positiveBackgroundColorHover    = ImVec4(0.0f, 0.3961f, 0.2431f, 1.0f),
    .positiveBackgroundColorKeyFocus = ImVec4(0.0f, 0.3961f, 0.2431f, 1.0f),
    .positiveColor100                = ImVec4(0.8078f, 0.9725f, 0.8784f, 1.0f),
    .positiveColor1000               = ImVec4(0.0f, 0.3961f, 0.2431f, 1.0f),
    .positiveColor1100               = ImVec4(0.0f, 0.3176f, 0.1961f, 1.0f),
    .positiveColor1200               = ImVec4(0.0196f, 0.2471f, 0.1529f, 1.0f),
    .positiveColor1300               = ImVec4(0.0392f, 0.1804f, 0.1137f, 1.0f),
    .positiveColor1400               = ImVec4(0.0392f, 0.1255f, 0.0824f, 1.0f),
    .positiveColor200                = ImVec4(0.6784f, 0.9569f, 0.8078f, 1.0f),
    .positiveColor300                = ImVec4(0.5373f, 0.9255f, 0.7373f, 1.0f),
    .positiveColor400                = ImVec4(0.4039f, 0.8706f, 0.6588f, 1.0f),
    .positiveColor500                = ImVec4(0.2863f, 0.8f, 0.5765f, 1.0f),
    .positiveColor600                = ImVec4(0.1843f, 0.7216f, 0.502f, 1.0f),
    .positiveColor700                = ImVec4(0.0824f, 0.6431f, 0.4314f, 1.0f),
    .positiveColor800                = ImVec4(0.0f, 0.5608f, 0.3647f, 1.0f),
    .positiveColor900                = ImVec4(0.0f, 0.4784f, 0.302f, 1.0f),
    .positiveVisualColor             = ImVec4(0.0824f, 0.6431f, 0.4314f, 1.0f),
    .purple100                       = ImVec4(0.9647f, 0.9216f, 1.0f, 1.0f),
    .purple1000                      = ImVec4(0.451f, 0.149f, 0.8275f, 1.0f),
    .purple1100                      = ImVec4(0.3647f, 0.0745f, 0.7176f, 1.0f),
    .purple1200                      = ImVec4(0.2784f, 0.0471f, 0.5804f, 1.0f),
    .purple1300                      = ImVec4(0.2f, 0.0627f, 0.4157f, 1.0f),
    .purple1400                      = ImVec4(0.1373f, 0.0588f, 0.2863f, 1.0f),
    .purple200                       = ImVec4(0.9333f, 0.8667f, 1.0f, 1.0f),
    .purple300                       = ImVec4(0.902f, 0.8157f, 1.0f, 1.0f),
    .purple400                       = ImVec4(0.8588f, 0.7333f, 0.9961f, 1.0f),
    .purple500                       = ImVec4(0.8f, 0.6431f, 0.9922f, 1.0f),
    .purple600                       = ImVec4(0.7412f, 0.5451f, 0.9882f, 1.0f),
    .purple700                       = ImVec4(0.6824f, 0.4471f, 0.9765f, 1.0f),
    .purple800                       = ImVec4(0.6157f, 0.3412f, 0.9569f, 1.0f),
    .purple900                       = ImVec4(0.5373f, 0.2392f, 0.9059f, 1.0f),
    .purpleBackgroundColorDefault    = ImVec4(0.5373f, 0.2392f, 0.9059f, 1.0f),
    .purpleVisualColor               = ImVec4(0.6157f, 0.3412f, 0.9569f, 1.0f),
    .red100                          = ImVec4(1.0f, 0.9216f, 0.9059f, 1.0f),
    .red1000                         = ImVec4(0.7059f, 0.0f, 0.0f, 1.0f),
    .red1100                         = ImVec4(0.5765f, 0.0f, 0.0f, 1.0f),
    .red1200                         = ImVec4(0.4549f, 0.0f, 0.0f, 1.0f),
    .red1300                         = ImVec4(0.349f, 0.0f, 0.0f, 1.0f),
    .red1400                         = ImVec4(0.2627f, 0.0f, 0.0f, 1.0f),
    .red200                          = ImVec4(1.0f, 0.8667f, 0.8392f, 1.0f),
    .red300                          = ImVec4(1.0f, 0.8039f, 0.7647f, 1.0f),
    .red400                          = ImVec4(1.0f, 0.7176f, 0.6627f, 1.0f),
    .red500                          = ImVec4(1.0f, 0.6078f, 0.5333f, 1.0f),
    .red600                          = ImVec4(1.0f, 0.4863f, 0.3961f, 1.0f),
    .red700                          = ImVec4(0.9686f, 0.3608f, 0.2745f, 1.0f),
    .red800                          = ImVec4(0.9176f, 0.2196f, 0.1608f, 1.0f),
    .red900                          = ImVec4(0.8275f, 0.0824f, 0.0627f, 1.0f),
    .redBackgroundColorDefault       = ImVec4(0.8275f, 0.0824f, 0.0627f, 1.0f),
    .redVisualColor                  = ImVec4(0.9176f, 0.2196f, 0.1608f, 1.0f),
    .seafoam100                      = ImVec4(0.8078f, 0.9686f, 0.9529f, 1.0f),
    .seafoam1000                     = ImVec4(0.0f, 0.3882f, 0.3725f, 1.0f),
    .seafoam1100                     = ImVec4(0.0471f, 0.3098f, 0.298f, 1.0f),
    .seafoam1200                     = ImVec4(0.0706f, 0.2353f, 0.2275f, 1.0f),
    .seafoam1300                     = ImVec4(0.0706f, 0.1725f, 0.1686f, 1.0f),
    .seafoam1400                     = ImVec4(0.0588f, 0.1216f, 0.1176f, 1.0f),
    .seafoam200                      = ImVec4(0.6667f, 0.9451f, 0.9176f, 1.0f),
    .seafoam300                      = ImVec4(0.549f, 0.9137f, 0.8863f, 1.0f),
    .seafoam400                      = ImVec4(0.3961f, 0.8549f, 0.8235f, 1.0f),
    .seafoam500                      = ImVec4(0.2471f, 0.7882f, 0.7569f, 1.0f),
    .seafoam600                      = ImVec4(0.0588f, 0.7098f, 0.6824f, 1.0f),
    .seafoam700                      = ImVec4(0.0f, 0.6314f, 0.6039f, 1.0f),
    .seafoam800                      = ImVec4(0.0f, 0.549f, 0.5294f, 1.0f),
    .seafoam900                      = ImVec4(0.0f, 0.4667f, 0.4471f, 1.0f),
    .seafoamBackgroundColorDefault   = ImVec4(0.0f, 0.4667f, 0.4471f, 1.0f),
    .seafoamVisualColor              = ImVec4(0.0f, 0.6314f, 0.6039f, 1.0f),
    .staticBlackFocusIndicatorColor  = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .staticBlue1000                  = ImVec4(0.1529f, 0.302f, 0.9176f, 1.0f),
    .staticBlue900                   = ImVec4(0.2314f, 0.3882f, 0.9843f, 1.0f),
    .staticFuchsia1000               = ImVec4(0.6118f, 0.1569f, 0.6863f, 1.0f),
    .staticFuchsia900                = ImVec4(0.7098f, 0.2235f, 0.7843f, 1.0f),
    .staticIndigo1000                = ImVec4(0.3882f, 0.2196f, 0.9333f, 1.0f),
    .staticIndigo900                 = ImVec4(0.4431f, 0.3333f, 0.9804f, 1.0f),
    .staticMagenta1000               = ImVec4(0.7294f, 0.0863f, 0.3137f, 1.0f),
    .staticMagenta900                = ImVec4(0.851f, 0.1373f, 0.3804f, 1.0f),
    .staticRed1000                   = ImVec4(0.7176f, 0.1569f, 0.0941f, 1.0f),
    .staticRed900                    = ImVec4(0.8431f, 0.1961f, 0.1255f, 1.0f),
    .staticWhiteFocusIndicatorColor  = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .swatchBorderColor               = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .swatchDisabledIconBorderColor   = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .tableRowHoverColor              = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .tableSelectedRowBackgroundColor = ImVec4(0.0078f, 0.3961f, 0.8627f, 1.0f),
    .tableSelectedRowBackgroundColorNonEmphasized =
        ImVec4(0.2745f, 0.2745f, 0.2745f, 1.0f),
    .thumbnailBorderColor         = ImVec4(0.1333f, 0.1333f, 0.1333f, 1.0f),
    .transparentBlack100          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack200          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack300          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack400          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack500          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack600          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack700          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack800          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack900          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentWhite100          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite200          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite300          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite400          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite500          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite600          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite700          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite800          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite900          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .white                        = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .yellow100                    = ImVec4(0.9843f, 0.9451f, 0.5961f, 1.0f),
    .yellow1000                   = ImVec4(0.4392f, 0.3255f, 0.0f, 1.0f),
    .yellow1100                   = ImVec4(0.3569f, 0.2627f, 0.0f, 1.0f),
    .yellow1200                   = ImVec4(0.2824f, 0.2f, 0.0f, 1.0f),
    .yellow1300                   = ImVec4(0.2118f, 0.1451f, 0.0f, 1.0f),
    .yellow1400                   = ImVec4(0.1569f, 0.102f, 0.0f, 1.0f),
    .yellow200                    = ImVec4(0.9725f, 0.9059f, 0.3137f, 1.0f),
    .yellow300                    = ImVec4(0.9725f, 0.851f, 0.0157f, 1.0f),
    .yellow400                    = ImVec4(0.9098f, 0.7765f, 0.0f, 1.0f),
    .yellow500                    = ImVec4(0.8431f, 0.702f, 0.0f, 1.0f),
    .yellow600                    = ImVec4(0.7686f, 0.6235f, 0.0f, 1.0f),
    .yellow700                    = ImVec4(0.6902f, 0.549f, 0.0f, 1.0f),
    .yellow800                    = ImVec4(0.6078f, 0.4706f, 0.0f, 1.0f),
    .yellow900                    = ImVec4(0.5216f, 0.4f, 0.0f, 1.0f),
    .yellowBackgroundColorDefault = ImVec4(0.9098f, 0.7765f, 0.0f, 1.0f),
    .yellowVisualColor            = ImVec4(0.7686f, 0.6235f, 0.0f, 1.0f),
};

static const SpectrumTokens spectrumDark{
    .accentBackgroundColorDefault     = ImVec4(0.0118f, 0.4039f, 0.8784f, 1.0f),
    .accentBackgroundColorDown        = ImVec4(0.0f, 0.302f, 0.6392f, 1.0f),
    .accentBackgroundColorHover       = ImVec4(0.0f, 0.349f, 0.7608f, 1.0f),
    .accentBackgroundColorKeyFocus    = ImVec4(0.0f, 0.349f, 0.7608f, 1.0f),
    .accentColor100                   = ImVec4(0.0f, 0.2196f, 0.4667f, 1.0f),
    .accentColor1000                  = ImVec4(0.5608f, 0.7922f, 0.9882f, 1.0f),
    .accentColor1100                  = ImVec4(0.6824f, 0.8588f, 0.9961f, 1.0f),
    .accentColor1200                  = ImVec4(0.8f, 0.9137f, 1.0f, 1.0f),
    .accentColor1300                  = ImVec4(0.9098f, 0.9647f, 1.0f, 1.0f),
    .accentColor1400                  = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .accentColor200                   = ImVec4(0.0f, 0.2549f, 0.5412f, 1.0f),
    .accentColor300                   = ImVec4(0.0f, 0.302f, 0.6392f, 1.0f),
    .accentColor400                   = ImVec4(0.0f, 0.349f, 0.7608f, 1.0f),
    .accentColor500                   = ImVec4(0.0118f, 0.4039f, 0.8784f, 1.0f),
    .accentColor600                   = ImVec4(0.0745f, 0.4745f, 0.9529f, 1.0f),
    .accentColor700                   = ImVec4(0.2039f, 0.5608f, 0.9569f, 1.0f),
    .accentColor800                   = ImVec4(0.3294f, 0.6392f, 0.9647f, 1.0f),
    .accentColor900                   = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .accentContentColorDefault        = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .accentContentColorDown           = ImVec4(0.6824f, 0.8588f, 0.9961f, 1.0f),
    .accentContentColorHover          = ImVec4(0.5608f, 0.7922f, 0.9882f, 1.0f),
    .accentContentColorKeyFocus       = ImVec4(0.5608f, 0.7922f, 0.9882f, 1.0f),
    .accentVisualColor                = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .backgroundBaseColor              = ImVec4(0.1137f, 0.1137f, 0.1137f, 1.0f),
    .backgroundLayer1Color            = ImVec4(0.149f, 0.149f, 0.149f, 1.0f),
    .backgroundLayer2Color            = ImVec4(0.1961f, 0.1961f, 0.1961f, 1.0f),
    .black                            = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .blue100                          = ImVec4(0.0f, 0.2196f, 0.4667f, 1.0f),
    .blue1000                         = ImVec4(0.5608f, 0.7922f, 0.9882f, 1.0f),
    .blue1100                         = ImVec4(0.6824f, 0.8588f, 0.9961f, 1.0f),
    .blue1200                         = ImVec4(0.8f, 0.9137f, 1.0f, 1.0f),
    .blue1300                         = ImVec4(0.9098f, 0.9647f, 1.0f, 1.0f),
    .blue1400                         = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .blue200                          = ImVec4(0.0f, 0.2549f, 0.5412f, 1.0f),
    .blue300                          = ImVec4(0.0f, 0.302f, 0.6392f, 1.0f),
    .blue400                          = ImVec4(0.0f, 0.349f, 0.7608f, 1.0f),
    .blue500                          = ImVec4(0.0118f, 0.4039f, 0.8784f, 1.0f),
    .blue600                          = ImVec4(0.0745f, 0.4745f, 0.9529f, 1.0f),
    .blue700                          = ImVec4(0.2039f, 0.5608f, 0.9569f, 1.0f),
    .blue800                          = ImVec4(0.3294f, 0.6392f, 0.9647f, 1.0f),
    .blue900                          = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .blueBackgroundColorDefault       = ImVec4(0.2039f, 0.5608f, 0.9569f, 1.0f),
    .blueVisualColor                  = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .bodyColor                        = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .cardSelectionBackgroundColor     = ImVec4(0.1961f, 0.1961f, 0.1961f, 1.0f),
    .celery100                        = ImVec4(0.0f, 0.2706f, 0.0392f, 1.0f),
    .celery1000                       = ImVec4(0.4118f, 0.8627f, 0.3882f, 1.0f),
    .celery1100                       = ImVec4(0.5569f, 0.9216f, 0.498f, 1.0f),
    .celery1200                       = ImVec4(0.7059f, 0.9686f, 0.6353f, 1.0f),
    .celery1300                       = ImVec4(0.8667f, 0.9922f, 0.8275f, 1.0f),
    .celery1400                       = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .celery200                        = ImVec4(0.0f, 0.3137f, 0.0471f, 1.0f),
    .celery300                        = ImVec4(0.0f, 0.3686f, 0.0549f, 1.0f),
    .celery400                        = ImVec4(0.0f, 0.4275f, 0.0588f, 1.0f),
    .celery500                        = ImVec4(0.0f, 0.498f, 0.0588f, 1.0f),
    .celery600                        = ImVec4(0.0f, 0.5686f, 0.0706f, 1.0f),
    .celery700                        = ImVec4(0.0157f, 0.6471f, 0.1176f, 1.0f),
    .celery800                        = ImVec4(0.1333f, 0.7216f, 0.2f, 1.0f),
    .celery900                        = ImVec4(0.2667f, 0.7922f, 0.2863f, 1.0f),
    .celeryBackgroundColorDefault     = ImVec4(0.1333f, 0.7216f, 0.2f, 1.0f),
    .celeryVisualColor                = ImVec4(0.1333f, 0.7216f, 0.2f, 1.0f),
    .chartreuse100                    = ImVec4(0.1882f, 0.251f, 0.0f, 1.0f),
    .chartreuse1000                   = ImVec4(0.651f, 0.8275f, 0.0706f, 1.0f),
    .chartreuse1100                   = ImVec4(0.7216f, 0.898f, 0.1451f, 1.0f),
    .chartreuse1200                   = ImVec4(0.8039f, 0.9608f, 0.2784f, 1.0f),
    .chartreuse1300                   = ImVec4(0.9059f, 0.9961f, 0.6039f, 1.0f),
    .chartreuse1400                   = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .chartreuse200                    = ImVec4(0.2157f, 0.2902f, 0.0f, 1.0f),
    .chartreuse300                    = ImVec4(0.2549f, 0.3412f, 0.0f, 1.0f),
    .chartreuse400                    = ImVec4(0.298f, 0.4f, 0.0f, 1.0f),
    .chartreuse500                    = ImVec4(0.349f, 0.4627f, 0.0f, 1.0f),
    .chartreuse600                    = ImVec4(0.4f, 0.5333f, 0.0f, 1.0f),
    .chartreuse700                    = ImVec4(0.4588f, 0.6039f, 0.0f, 1.0f),
    .chartreuse800                    = ImVec4(0.5176f, 0.6784f, 0.0039f, 1.0f),
    .chartreuse900                    = ImVec4(0.5804f, 0.7529f, 0.0314f, 1.0f),
    .chartreuseBackgroundColorDefault = ImVec4(0.5804f, 0.7529f, 0.0314f, 1.0f),
    .chartreuseVisualColor            = ImVec4(0.5804f, 0.7529f, 0.0314f, 1.0f),
    .coachMarkPaginationColor         = ImVec4(0.698f, 0.698f, 0.698f, 1.0f),
    .codeColor                        = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .colorAreaBorderColor             = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .colorHandleDropShadowColor       = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorHandleInnerBorderColor      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorHandleOuterBorderColor      = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorLoupeDropShadowColor        = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorLoupeInnerBorder            = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .colorLoupeOuterBorder            = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .colorSliderBorderColor           = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .cyan100                          = ImVec4(0.0f, 0.2392f, 0.3843f, 1.0f),
    .cyan1000                         = ImVec4(0.3294f, 0.8275f, 0.9451f, 1.0f),
    .cyan1100                         = ImVec4(0.498f, 0.8941f, 0.9765f, 1.0f),
    .cyan1200                         = ImVec4(0.6549f, 0.9451f, 1.0f, 1.0f),
    .cyan1300                         = ImVec4(0.8431f, 0.9804f, 1.0f, 1.0f),
    .cyan1400                         = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .cyan200                          = ImVec4(0.0f, 0.2784f, 0.4353f, 1.0f),
    .cyan300                          = ImVec4(0.0f, 0.3333f, 0.498f, 1.0f),
    .cyan400                          = ImVec4(0.0f, 0.3922f, 0.5686f, 1.0f),
    .cyan500                          = ImVec4(0.0f, 0.4549f, 0.6353f, 1.0f),
    .cyan600                          = ImVec4(0.0f, 0.5255f, 0.7059f, 1.0f),
    .cyan700                          = ImVec4(0.0f, 0.6f, 0.7765f, 1.0f),
    .cyan800                          = ImVec4(0.0549f, 0.6784f, 0.8431f, 1.0f),
    .cyan900                          = ImVec4(0.1725f, 0.7569f, 0.902f, 1.0f),
    .cyanBackgroundColorDefault       = ImVec4(0.0f, 0.6f, 0.7765f, 1.0f),
    .cyanVisualColor                  = ImVec4(0.1725f, 0.7569f, 0.902f, 1.0f),
    .detailColor                      = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .disabledBackgroundColor          = ImVec4(0.2471f, 0.2471f, 0.2471f, 1.0f),
    .disabledBorderColor              = ImVec4(0.3294f, 0.3294f, 0.3294f, 1.0f),
    .disabledContentColor             = ImVec4(0.4392f, 0.4392f, 0.4392f, 1.0f),
    .disabledStaticBlackBackgroundColor = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .disabledStaticBlackBorderColor     = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .disabledStaticBlackContentColor    = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .disabledStaticWhiteBackgroundColor = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .disabledStaticWhiteBorderColor     = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .disabledStaticWhiteContentColor    = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .dropShadowColor                    = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .dropZoneBackgroundColor = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .floatingActionButtonDropShadowColor = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .floatingActionButtonShadowColor     = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .focusIndicatorColor           = ImVec4(0.3294f, 0.6392f, 0.9647f, 1.0f),
    .fuchsia100                    = ImVec4(0.4196f, 0.0118f, 0.4157f, 1.0f),
    .fuchsia1000                   = ImVec4(0.9804f, 0.6588f, 0.9608f, 1.0f),
    .fuchsia1100                   = ImVec4(0.9961f, 0.7608f, 0.9725f, 1.0f),
    .fuchsia1200                   = ImVec4(1.0f, 0.8588f, 0.9804f, 1.0f),
    .fuchsia1300                   = ImVec4(1.0f, 0.9373f, 0.9882f, 1.0f),
    .fuchsia1400                   = ImVec4(1.0f, 0.9922f, 1.0f, 1.0f),
    .fuchsia200                    = ImVec4(0.4824f, 0.0f, 0.4824f, 1.0f),
    .fuchsia300                    = ImVec4(0.5647f, 0.0f, 0.5686f, 1.0f),
    .fuchsia400                    = ImVec4(0.6471f, 0.051f, 0.651f, 1.0f),
    .fuchsia500                    = ImVec4(0.7255f, 0.1451f, 0.7255f, 1.0f),
    .fuchsia600                    = ImVec4(0.8039f, 0.2235f, 0.8078f, 1.0f),
    .fuchsia700                    = ImVec4(0.8745f, 0.3176f, 0.8784f, 1.0f),
    .fuchsia800                    = ImVec4(0.9216f, 0.4314f, 0.9255f, 1.0f),
    .fuchsia900                    = ImVec4(0.9569f, 0.549f, 0.949f, 1.0f),
    .fuchsiaBackgroundColorDefault = ImVec4(0.8745f, 0.3176f, 0.8784f, 1.0f),
    .fuchsiaVisualColor            = ImVec4(0.9569f, 0.549f, 0.949f, 1.0f),
    .gray100                       = ImVec4(0.1961f, 0.1961f, 0.1961f, 1.0f),
    .gray200                       = ImVec4(0.2471f, 0.2471f, 0.2471f, 1.0f),
    .gray300                       = ImVec4(0.3294f, 0.3294f, 0.3294f, 1.0f),
    .gray400                       = ImVec4(0.4392f, 0.4392f, 0.4392f, 1.0f),
    .gray50                        = ImVec4(0.1137f, 0.1137f, 0.1137f, 1.0f),
    .gray500                       = ImVec4(0.5647f, 0.5647f, 0.5647f, 1.0f),
    .gray600                       = ImVec4(0.698f, 0.698f, 0.698f, 1.0f),
    .gray700                       = ImVec4(0.8196f, 0.8196f, 0.8196f, 1.0f),
    .gray75                        = ImVec4(0.149f, 0.149f, 0.149f, 1.0f),
    .gray800                       = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .gray900                       = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .grayBackgroundColorDefault    = ImVec4(0.8196f, 0.8196f, 0.8196f, 1.0f),
    .grayVisualColor               = ImVec4(0.698f, 0.698f, 0.698f, 1.0f),
    .green100                      = ImVec4(0.0157f, 0.2627f, 0.1608f, 1.0f),
    .green1000                     = ImVec4(0.3686f, 0.851f, 0.6353f, 1.0f),
    .green1100                     = ImVec4(0.5059f, 0.9137f, 0.7216f, 1.0f),
    .green1200                     = ImVec4(0.6941f, 0.9569f, 0.8196f, 1.0f),
    .green1300                     = ImVec4(0.8745f, 0.9804f, 0.9176f, 1.0f),
    .green1400                     = ImVec4(0.9961f, 1.0f, 0.9882f, 1.0f),
    .green200                      = ImVec4(0.0f, 0.3059f, 0.1843f, 1.0f),
    .green300                      = ImVec4(0.0f, 0.3608f, 0.2196f, 1.0f),
    .green400                      = ImVec4(0.0f, 0.4235f, 0.2627f, 1.0f),
    .green500                      = ImVec4(0.0f, 0.4902f, 0.3059f, 1.0f),
    .green600                      = ImVec4(0.0f, 0.5608f, 0.3647f, 1.0f),
    .green700                      = ImVec4(0.0706f, 0.6353f, 0.4235f, 1.0f),
    .green800                      = ImVec4(0.1686f, 0.7059f, 0.4902f, 1.0f),
    .green900                      = ImVec4(0.2627f, 0.7804f, 0.5608f, 1.0f),
    .greenBackgroundColorDefault   = ImVec4(0.0706f, 0.6353f, 0.4235f, 1.0f),
    .greenVisualColor              = ImVec4(0.1686f, 0.7059f, 0.4902f, 1.0f),
    .headingColor                  = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .iconColorBluePrimaryDefault   = ImVec4(0.3294f, 0.6392f, 0.9647f, 1.0f),
    .iconColorGreenPrimaryDefault  = ImVec4(0.1686f, 0.7059f, 0.4902f, 1.0f),
    .iconColorInverse              = ImVec4(0.1137f, 0.1137f, 0.1137f, 1.0f),
    .iconColorPrimaryDefault       = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .iconColorRedPrimaryDefault    = ImVec4(0.9647f, 0.3451f, 0.2627f, 1.0f),
    .iconColorYellowPrimaryDefault = ImVec4(0.8941f, 0.7608f, 0.0f, 1.0f),
    .indigo100                     = ImVec4(0.1569f, 0.1725f, 0.549f, 1.0f),
    .indigo1000                    = ImVec4(0.7373f, 0.7451f, 1.0f, 1.0f),
    .indigo1100                    = ImVec4(0.8157f, 0.8235f, 1.0f, 1.0f),
    .indigo1200                    = ImVec4(0.8863f, 0.8941f, 1.0f, 1.0f),
    .indigo1300                    = ImVec4(0.9529f, 0.9529f, 0.9961f, 1.0f),
    .indigo1400                    = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .indigo200                     = ImVec4(0.1843f, 0.2039f, 0.6392f, 1.0f),
    .indigo300                     = ImVec4(0.2235f, 0.2471f, 0.7333f, 1.0f),
    .indigo400                     = ImVec4(0.2745f, 0.2941f, 0.8275f, 1.0f),
    .indigo500                     = ImVec4(0.3333f, 0.3569f, 0.9059f, 1.0f),
    .indigo600                     = ImVec4(0.4078f, 0.4275f, 0.9569f, 1.0f),
    .indigo700                     = ImVec4(0.4863f, 0.5059f, 0.9843f, 1.0f),
    .indigo800                     = ImVec4(0.5686f, 0.5843f, 1.0f, 1.0f),
    .indigo900                     = ImVec4(0.6549f, 0.6667f, 1.0f, 1.0f),
    .indigoBackgroundColorDefault  = ImVec4(0.4863f, 0.5059f, 0.9843f, 1.0f),
    .indigoVisualColor             = ImVec4(0.6549f, 0.6667f, 1.0f, 1.0f),
    .informativeBackgroundColorDefault =
        ImVec4(0.0118f, 0.4039f, 0.8784f, 1.0f),
    .informativeBackgroundColorDown     = ImVec4(0.0f, 0.302f, 0.6392f, 1.0f),
    .informativeBackgroundColorHover    = ImVec4(0.0f, 0.349f, 0.7608f, 1.0f),
    .informativeBackgroundColorKeyFocus = ImVec4(0.0f, 0.349f, 0.7608f, 1.0f),
    .informativeColor100                = ImVec4(0.0f, 0.2196f, 0.4667f, 1.0f),
    .informativeColor1000            = ImVec4(0.5608f, 0.7922f, 0.9882f, 1.0f),
    .informativeColor1100            = ImVec4(0.6824f, 0.8588f, 0.9961f, 1.0f),
    .informativeColor1200            = ImVec4(0.8f, 0.9137f, 1.0f, 1.0f),
    .informativeColor1300            = ImVec4(0.9098f, 0.9647f, 1.0f, 1.0f),
    .informativeColor1400            = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .informativeColor200             = ImVec4(0.0f, 0.2549f, 0.5412f, 1.0f),
    .informativeColor300             = ImVec4(0.0f, 0.302f, 0.6392f, 1.0f),
    .informativeColor400             = ImVec4(0.0f, 0.349f, 0.7608f, 1.0f),
    .informativeColor500             = ImVec4(0.0118f, 0.4039f, 0.8784f, 1.0f),
    .informativeColor600             = ImVec4(0.0745f, 0.4745f, 0.9529f, 1.0f),
    .informativeColor700             = ImVec4(0.2039f, 0.5608f, 0.9569f, 1.0f),
    .informativeColor800             = ImVec4(0.3294f, 0.6392f, 0.9647f, 1.0f),
    .informativeColor900             = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .informativeVisualColor          = ImVec4(0.4471f, 0.7176f, 0.9765f, 1.0f),
    .magenta100                      = ImVec4(0.4627f, 0.0f, 0.2275f, 1.0f),
    .magenta1000                     = ImVec4(1.0f, 0.6745f, 0.7922f, 1.0f),
    .magenta1100                     = ImVec4(1.0f, 0.7765f, 0.8549f, 1.0f),
    .magenta1200                     = ImVec4(1.0f, 0.8667f, 0.9137f, 1.0f),
    .magenta1300                     = ImVec4(1.0f, 0.9412f, 0.9608f, 1.0f),
    .magenta1400                     = ImVec4(1.0f, 0.9882f, 0.9922f, 1.0f),
    .magenta200                      = ImVec4(0.5373f, 0.0f, 0.2588f, 1.0f),
    .magenta300                      = ImVec4(0.6275f, 0.0f, 0.302f, 1.0f),
    .magenta400                      = ImVec4(0.7137f, 0.0706f, 0.3529f, 1.0f),
    .magenta500                      = ImVec4(0.7961f, 0.149f, 0.4275f, 1.0f),
    .magenta600                      = ImVec4(0.8706f, 0.2392f, 0.5098f, 1.0f),
    .magenta700                      = ImVec4(0.9294f, 0.3412f, 0.5843f, 1.0f),
    .magenta800                      = ImVec4(0.9765f, 0.4471f, 0.6549f, 1.0f),
    .magenta900                      = ImVec4(1.0f, 0.5608f, 0.7255f, 1.0f),
    .magentaBackgroundColorDefault   = ImVec4(0.9294f, 0.3412f, 0.5843f, 1.0f),
    .magentaVisualColor              = ImVec4(1.0f, 0.5608f, 0.7255f, 1.0f),
    .negativeBackgroundColorDefault  = ImVec4(0.8431f, 0.098f, 0.0745f, 1.0f),
    .negativeBackgroundColorDown     = ImVec4(0.6471f, 0.0f, 0.0f, 1.0f),
    .negativeBackgroundColorHover    = ImVec4(0.7451f, 0.0157f, 0.0118f, 1.0f),
    .negativeBackgroundColorKeyFocus = ImVec4(0.7451f, 0.0157f, 0.0118f, 1.0f),
    .negativeBorderColorDefault      = ImVec4(1.0f, 0.5843f, 0.5059f, 1.0f),
    .negativeBorderColorDown         = ImVec4(1.0f, 0.7882f, 0.7412f, 1.0f),
    .negativeBorderColorFocus        = ImVec4(1.0f, 0.6902f, 0.6314f, 1.0f),
    .negativeBorderColorFocusHover   = ImVec4(1.0f, 0.7882f, 0.7412f, 1.0f),
    .negativeBorderColorHover        = ImVec4(1.0f, 0.6902f, 0.6314f, 1.0f),
    .negativeBorderColorKeyFocus     = ImVec4(1.0f, 0.6902f, 0.6314f, 1.0f),
    .negativeColor100                = ImVec4(0.4824f, 0.0f, 0.0f, 1.0f),
    .negativeColor1000               = ImVec4(1.0f, 0.6902f, 0.6314f, 1.0f),
    .negativeColor1100               = ImVec4(1.0f, 0.7882f, 0.7412f, 1.0f),
    .negativeColor1200               = ImVec4(1.0f, 0.8706f, 0.8471f, 1.0f),
    .negativeColor1300               = ImVec4(1.0f, 0.9451f, 0.9333f, 1.0f),
    .negativeColor1400               = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .negativeColor200                = ImVec4(0.5529f, 0.0f, 0.0f, 1.0f),
    .negativeColor300                = ImVec4(0.6471f, 0.0f, 0.0f, 1.0f),
    .negativeColor400                = ImVec4(0.7451f, 0.0157f, 0.0118f, 1.0f),
    .negativeColor500                = ImVec4(0.8431f, 0.098f, 0.0745f, 1.0f),
    .negativeColor600                = ImVec4(0.9176f, 0.2196f, 0.1608f, 1.0f),
    .negativeColor700                = ImVec4(0.9647f, 0.3451f, 0.2627f, 1.0f),
    .negativeColor800                = ImVec4(1.0f, 0.4588f, 0.3686f, 1.0f),
    .negativeColor900                = ImVec4(1.0f, 0.5843f, 0.5059f, 1.0f),
    .negativeContentColorDefault     = ImVec4(1.0f, 0.5843f, 0.5059f, 1.0f),
    .negativeContentColorDown        = ImVec4(1.0f, 0.7882f, 0.7412f, 1.0f),
    .negativeContentColorHover       = ImVec4(1.0f, 0.6902f, 0.6314f, 1.0f),
    .negativeContentColorKeyFocus    = ImVec4(1.0f, 0.6902f, 0.6314f, 1.0f),
    .negativeVisualColor             = ImVec4(0.9647f, 0.3451f, 0.2627f, 1.0f),
    .neutralBackgroundColorDefault   = ImVec4(0.4392f, 0.4392f, 0.4392f, 1.0f),
    .neutralBackgroundColorDown      = ImVec4(0.2471f, 0.2471f, 0.2471f, 1.0f),
    .neutralBackgroundColorHover     = ImVec4(0.3294f, 0.3294f, 0.3294f, 1.0f),
    .neutralBackgroundColorKeyFocus  = ImVec4(0.3294f, 0.3294f, 0.3294f, 1.0f),
    .neutralBackgroundColorSelectedDefault =
        ImVec4(0.8196f, 0.8196f, 0.8196f, 1.0f),
    .neutralBackgroundColorSelectedDown = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralBackgroundColorSelectedHover =
        ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .neutralBackgroundColorSelectedKeyFocus =
        ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .neutralContentColorDefault    = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .neutralContentColorDown       = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralContentColorFocus      = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralContentColorFocusHover = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralContentColorHover      = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralContentColorKeyFocus   = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralSubduedBackgroundColorDefault =
        ImVec4(0.4392f, 0.4392f, 0.4392f, 1.0f),
    .neutralSubduedBackgroundColorDown =
        ImVec4(0.2471f, 0.2471f, 0.2471f, 1.0f),
    .neutralSubduedBackgroundColorHover =
        ImVec4(0.3294f, 0.3294f, 0.3294f, 1.0f),
    .neutralSubduedBackgroundColorKeyFocus =
        ImVec4(0.3294f, 0.3294f, 0.3294f, 1.0f),
    .neutralSubduedContentColorDefault =
        ImVec4(0.8196f, 0.8196f, 0.8196f, 1.0f),
    .neutralSubduedContentColorDown  = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralSubduedContentColorHover = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .neutralSubduedContentColorKeyFocus =
        ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .neutralSubduedContentColorSelected = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .neutralVisualColor                 = ImVec4(0.698f, 0.698f, 0.698f, 1.0f),
    .noticeBackgroundColorDefault    = ImVec4(0.9569f, 0.5059f, 0.0471f, 1.0f),
    .noticeColor100                  = ImVec4(0.4f, 0.1451f, 0.0f, 1.0f),
    .noticeColor1000                 = ImVec4(1.0f, 0.7098f, 0.3451f, 1.0f),
    .noticeColor1100                 = ImVec4(0.9922f, 0.8078f, 0.5333f, 1.0f),
    .noticeColor1200                 = ImVec4(1.0f, 0.8824f, 0.702f, 1.0f),
    .noticeColor1300                 = ImVec4(1.0f, 0.949f, 0.8667f, 1.0f),
    .noticeColor1400                 = ImVec4(1.0f, 0.9922f, 0.9765f, 1.0f),
    .noticeColor200                  = ImVec4(0.4588f, 0.1765f, 0.0f, 1.0f),
    .noticeColor300                  = ImVec4(0.5373f, 0.2157f, 0.0f, 1.0f),
    .noticeColor400                  = ImVec4(0.6196f, 0.2588f, 0.0f, 1.0f),
    .noticeColor500                  = ImVec4(0.7059f, 0.3059f, 0.0f, 1.0f),
    .noticeColor600                  = ImVec4(0.7922f, 0.3647f, 0.0f, 1.0f),
    .noticeColor700                  = ImVec4(0.8824f, 0.4275f, 0.0f, 1.0f),
    .noticeColor800                  = ImVec4(0.9569f, 0.5059f, 0.0471f, 1.0f),
    .noticeColor900                  = ImVec4(0.9961f, 0.6039f, 0.1804f, 1.0f),
    .noticeVisualColor               = ImVec4(0.9961f, 0.6039f, 0.1804f, 1.0f),
    .opacityCheckerboardSquareDark   = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .opacityCheckerboardSquareLight  = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .orange100                       = ImVec4(0.4f, 0.1451f, 0.0f, 1.0f),
    .orange1000                      = ImVec4(1.0f, 0.7098f, 0.3451f, 1.0f),
    .orange1100                      = ImVec4(0.9922f, 0.8078f, 0.5333f, 1.0f),
    .orange1200                      = ImVec4(1.0f, 0.8824f, 0.702f, 1.0f),
    .orange1300                      = ImVec4(1.0f, 0.949f, 0.8667f, 1.0f),
    .orange1400                      = ImVec4(1.0f, 0.9922f, 0.9765f, 1.0f),
    .orange200                       = ImVec4(0.4588f, 0.1765f, 0.0f, 1.0f),
    .orange300                       = ImVec4(0.5373f, 0.2157f, 0.0f, 1.0f),
    .orange400                       = ImVec4(0.6196f, 0.2588f, 0.0f, 1.0f),
    .orange500                       = ImVec4(0.7059f, 0.3059f, 0.0f, 1.0f),
    .orange600                       = ImVec4(0.7922f, 0.3647f, 0.0f, 1.0f),
    .orange700                       = ImVec4(0.8824f, 0.4275f, 0.0f, 1.0f),
    .orange800                       = ImVec4(0.9569f, 0.5059f, 0.0471f, 1.0f),
    .orange900                       = ImVec4(0.9961f, 0.6039f, 0.1804f, 1.0f),
    .orangeBackgroundColorDefault    = ImVec4(0.9569f, 0.5059f, 0.0471f, 1.0f),
    .orangeVisualColor               = ImVec4(0.9961f, 0.6039f, 0.1804f, 1.0f),
    .overlayColor                    = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .positiveBackgroundColorDefault  = ImVec4(0.0f, 0.4902f, 0.3059f, 1.0f),
    .positiveBackgroundColorDown     = ImVec4(0.0f, 0.3608f, 0.2196f, 1.0f),
    .positiveBackgroundColorHover    = ImVec4(0.0f, 0.4235f, 0.2627f, 1.0f),
    .positiveBackgroundColorKeyFocus = ImVec4(0.0f, 0.4235f, 0.2627f, 1.0f),
    .positiveColor100                = ImVec4(0.0157f, 0.2627f, 0.1608f, 1.0f),
    .positiveColor1000               = ImVec4(0.3686f, 0.851f, 0.6353f, 1.0f),
    .positiveColor1100               = ImVec4(0.5059f, 0.9137f, 0.7216f, 1.0f),
    .positiveColor1200               = ImVec4(0.6941f, 0.9569f, 0.8196f, 1.0f),
    .positiveColor1300               = ImVec4(0.8745f, 0.9804f, 0.9176f, 1.0f),
    .positiveColor1400               = ImVec4(0.9961f, 1.0f, 0.9882f, 1.0f),
    .positiveColor200                = ImVec4(0.0f, 0.3059f, 0.1843f, 1.0f),
    .positiveColor300                = ImVec4(0.0f, 0.3608f, 0.2196f, 1.0f),
    .positiveColor400                = ImVec4(0.0f, 0.4235f, 0.2627f, 1.0f),
    .positiveColor500                = ImVec4(0.0f, 0.4902f, 0.3059f, 1.0f),
    .positiveColor600                = ImVec4(0.0f, 0.5608f, 0.3647f, 1.0f),
    .positiveColor700                = ImVec4(0.0706f, 0.6353f, 0.4235f, 1.0f),
    .positiveColor800                = ImVec4(0.1686f, 0.7059f, 0.4902f, 1.0f),
    .positiveColor900                = ImVec4(0.2627f, 0.7804f, 0.5608f, 1.0f),
    .positiveVisualColor             = ImVec4(0.1686f, 0.7059f, 0.4902f, 1.0f),
    .purple100                       = ImVec4(0.298f, 0.051f, 0.6157f, 1.0f),
    .purple1000                      = ImVec4(0.8431f, 0.7137f, 0.9961f, 1.0f),
    .purple1100                      = ImVec4(0.8941f, 0.8f, 0.9961f, 1.0f),
    .purple1200                      = ImVec4(0.9373f, 0.8745f, 1.0f, 1.0f),
    .purple1300                      = ImVec4(0.9765f, 0.9412f, 1.0f, 1.0f),
    .purple1400                      = ImVec4(1.0f, 0.9922f, 1.0f, 1.0f),
    .purple200                       = ImVec4(0.349f, 0.0667f, 0.6941f, 1.0f),
    .purple300                       = ImVec4(0.4118f, 0.1098f, 0.7843f, 1.0f),
    .purple400                       = ImVec4(0.4784f, 0.1765f, 0.8549f, 1.0f),
    .purple500                       = ImVec4(0.549f, 0.2549f, 0.9137f, 1.0f),
    .purple600                       = ImVec4(0.6157f, 0.3412f, 0.9529f, 1.0f),
    .purple700                       = ImVec4(0.6745f, 0.4353f, 0.9765f, 1.0f),
    .purple800                       = ImVec4(0.7333f, 0.5294f, 0.9843f, 1.0f),
    .purple900                       = ImVec4(0.7922f, 0.6235f, 0.9882f, 1.0f),
    .purpleBackgroundColorDefault    = ImVec4(0.6745f, 0.4353f, 0.9765f, 1.0f),
    .purpleVisualColor               = ImVec4(0.7922f, 0.6235f, 0.9882f, 1.0f),
    .red100                          = ImVec4(0.4824f, 0.0f, 0.0f, 1.0f),
    .red1000                         = ImVec4(1.0f, 0.6902f, 0.6314f, 1.0f),
    .red1100                         = ImVec4(1.0f, 0.7882f, 0.7412f, 1.0f),
    .red1200                         = ImVec4(1.0f, 0.8706f, 0.8471f, 1.0f),
    .red1300                         = ImVec4(1.0f, 0.9451f, 0.9333f, 1.0f),
    .red1400                         = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .red200                          = ImVec4(0.5529f, 0.0f, 0.0f, 1.0f),
    .red300                          = ImVec4(0.6471f, 0.0f, 0.0f, 1.0f),
    .red400                          = ImVec4(0.7451f, 0.0157f, 0.0118f, 1.0f),
    .red500                          = ImVec4(0.8431f, 0.098f, 0.0745f, 1.0f),
    .red600                          = ImVec4(0.9176f, 0.2196f, 0.1608f, 1.0f),
    .red700                          = ImVec4(0.9647f, 0.3451f, 0.2627f, 1.0f),
    .red800                          = ImVec4(1.0f, 0.4588f, 0.3686f, 1.0f),
    .red900                          = ImVec4(1.0f, 0.5843f, 0.5059f, 1.0f),
    .redBackgroundColorDefault       = ImVec4(0.9647f, 0.3451f, 0.2627f, 1.0f),
    .redVisualColor                  = ImVec4(0.9647f, 0.3451f, 0.2627f, 1.0f),
    .seafoam100                      = ImVec4(0.0706f, 0.2549f, 0.2471f, 1.0f),
    .seafoam1000                     = ImVec4(0.3647f, 0.8392f, 0.8118f, 1.0f),
    .seafoam1100                     = ImVec4(0.5176f, 0.902f, 0.8745f, 1.0f),
    .seafoam1200                     = ImVec4(0.6902f, 0.949f, 0.9255f, 1.0f),
    .seafoam1300                     = ImVec4(0.8745f, 0.9765f, 0.9647f, 1.0f),
    .seafoam1400                     = ImVec4(0.9961f, 1.0f, 0.9961f, 1.0f),
    .seafoam200                      = ImVec4(0.0549f, 0.298f, 0.2863f, 1.0f),
    .seafoam300                      = ImVec4(0.0157f, 0.3529f, 0.3412f, 1.0f),
    .seafoam400                      = ImVec4(0.0f, 0.4118f, 0.3961f, 1.0f),
    .seafoam500                      = ImVec4(0.0f, 0.4784f, 0.4588f, 1.0f),
    .seafoam600                      = ImVec4(0.0f, 0.549f, 0.5294f, 1.0f),
    .seafoam700                      = ImVec4(0.0f, 0.6196f, 0.5961f, 1.0f),
    .seafoam800                      = ImVec4(0.0118f, 0.698f, 0.6706f, 1.0f),
    .seafoam900                      = ImVec4(0.2118f, 0.7725f, 0.7412f, 1.0f),
    .seafoamBackgroundColorDefault   = ImVec4(0.0f, 0.6196f, 0.5961f, 1.0f),
    .seafoamVisualColor              = ImVec4(0.0118f, 0.698f, 0.6706f, 1.0f),
    .staticBlackFocusIndicatorColor  = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .staticBlue1000                  = ImVec4(0.1529f, 0.302f, 0.9176f, 1.0f),
    .staticBlue900                   = ImVec4(0.2314f, 0.3882f, 0.9843f, 1.0f),
    .staticFuchsia1000               = ImVec4(0.6118f, 0.1569f, 0.6863f, 1.0f),
    .staticFuchsia900                = ImVec4(0.7098f, 0.2235f, 0.7843f, 1.0f),
    .staticIndigo1000                = ImVec4(0.3882f, 0.2196f, 0.9333f, 1.0f),
    .staticIndigo900                 = ImVec4(0.4431f, 0.3333f, 0.9804f, 1.0f),
    .staticMagenta1000               = ImVec4(0.7294f, 0.0863f, 0.3137f, 1.0f),
    .staticMagenta900                = ImVec4(0.851f, 0.1373f, 0.3804f, 1.0f),
    .staticRed1000                   = ImVec4(0.7176f, 0.1569f, 0.0941f, 1.0f),
    .staticRed900                    = ImVec4(0.8431f, 0.1961f, 0.1255f, 1.0f),
    .staticWhiteFocusIndicatorColor  = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .swatchBorderColor               = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .swatchDisabledIconBorderColor   = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .tableRowHoverColor              = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .tableSelectedRowBackgroundColor = ImVec4(0.0118f, 0.4039f, 0.8784f, 1.0f),
    .tableSelectedRowBackgroundColorNonEmphasized =
        ImVec4(0.8196f, 0.8196f, 0.8196f, 1.0f),
    .thumbnailBorderColor         = ImVec4(0.9216f, 0.9216f, 0.9216f, 1.0f),
    .transparentBlack100          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack200          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack300          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack400          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack500          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack600          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack700          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack800          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentBlack900          = ImVec4(0.0f, 0.0f, 0.0f, 1.0f),
    .transparentWhite100          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite200          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite300          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite400          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite500          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite600          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite700          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite800          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .transparentWhite900          = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .white                        = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .yellow100                    = ImVec4(0.298f, 0.2118f, 0.0f, 1.0f),
    .yellow1000                   = ImVec4(0.8941f, 0.7608f, 0.0f, 1.0f),
    .yellow1100                   = ImVec4(0.9569f, 0.8353f, 0.0f, 1.0f),
    .yellow1200                   = ImVec4(0.9765f, 0.9098f, 0.3608f, 1.0f),
    .yellow1300                   = ImVec4(0.9882f, 0.9647f, 0.7333f, 1.0f),
    .yellow1400                   = ImVec4(1.0f, 1.0f, 1.0f, 1.0f),
    .yellow200                    = ImVec4(0.3451f, 0.251f, 0.0f, 1.0f),
    .yellow300                    = ImVec4(0.4039f, 0.298f, 0.0f, 1.0f),
    .yellow400                    = ImVec4(0.4667f, 0.349f, 0.0f, 1.0f),
    .yellow500                    = ImVec4(0.5333f, 0.4078f, 0.0f, 1.0f),
    .yellow600                    = ImVec4(0.6078f, 0.4706f, 0.0f, 1.0f),
    .yellow700                    = ImVec4(0.6824f, 0.5373f, 0.0f, 1.0f),
    .yellow800                    = ImVec4(0.7529f, 0.6118f, 0.0f, 1.0f),
    .yellow900                    = ImVec4(0.8275f, 0.6824f, 0.0f, 1.0f),
    .yellowBackgroundColorDefault = ImVec4(0.8941f, 0.7608f, 0.0f, 1.0f),
    .yellowVisualColor            = ImVec4(0.9569f, 0.8353f, 0.0f, 1.0f),
};

#endif
