[macos]
build:
    cargo clean -p ai-deno
    cargo build --release

[macos]
watch:
    cargo clean -p ai-deno
    cargo watch -x "build --release"

[macos]
watch-example:
    cargo watch -x "run example"