[macos]
run-ai:
    echo '' > illustrator.log
    RUST_BACKTRACE=full /Applications/Adobe\ Illustrator\ 2025/Adobe\ Illustrator.app/Contents/MacOS/Adobe\ Illustrator 2>&1 | tee -a illustrator.log

[macos]
watch:
    sudo deno run -A ./watch-sync.ts

[macos]
show-externs:
    nm -m output/mac/release/IllustratorDeno.aip/Contents/MacOS/IllustratorDeno

cpp-sandbox:
    clear
    clang++ -std=c++23 ./Sandbox/main.cpp -o /tmp/sandbox_bin
    /tmp/sandbox_bin
    rm /tmp/sandbox_bin
